### ISSUE TITLE
Using the camera 

### ISSUE THREAD

**Issue by ElSordo** [RedRobotics/RedBoard#2]
I noticed that the RedBoard does not have a thru slot for the camera cable.  There is not much clearance between the RedBoard and the RPi 3 (assuming that the RedBoard is on top of the RPI3) so the camera cable must be bent in order to route between the two boards.  Will this damage the camera ribbon cable?

What other alternatives would you suggest for handling the camera.  The goal is to build a donkey car (donkeykar.com) - it makes heavy use of machine vision.

**Comment by NeilLambeth** [comment]
I've updated the RedBoard Guide image with a label showing the position of the camera cable slot.
