### ISSUE TITLE
Incorrect Voltage - 3s Pack

### ISSUE THREAD

**Issue by kneave** [RedRobotics/RedBoard#3]
I'm running a 3s pack and when I run the system_monitor.py script it reports that the voltage is around half the actual voltage and starts complaining.  I've been playing around with different values but not sure what to use for the voltage divider.

https://github.com/RedRobotics/RedBoard/blob/5188fc80f7ce223eb17c4ccca501d80295c8b435/system/system_monitor.py#L76

batt_check reports 11.6 when my voltmeter shows around 12.2, could I ask for some guidance on this value please?

**Comment by NeilLambeth** [comment]
I've added a way of calibrating the ADC, and I've added a section on it in the instructions.
