### ISSUE TITLE
Not all servo outputs set up

### ISSUE THREAD

**Issue by dquill78** [RedRobotics/RedBoard#4]
Why were servo outputs 7, 8, 9, 10, 11 and 12 left out of redboard.py, and thus not set up already to be used? Was this an oversight or is there a problem?

**Comment by NeilLambeth** [comment]
Just an oversight, I'll add the other servo outputs to redboard.py.

**Comment by dquill78** [comment]
Cool. Thanks for getting back to me. I modified my redboard.py to set up
some of them but wasn't sure if there was maybe an intentional reason whey
they were left out.

Cheers!

**Comment by NeilLambeth** [comment]
I've just updated redboard.py with all the servos set up.
